import type { Metadata } from 'next'
import './globals.scss'
// app/layout.tsx hoặc pages/_app.tsx
import 'swiper/css'
import 'swiper/css/grid'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/effect-fade'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`font-primary antialiased`}>
                <main>{children}</main>
            </body>
        </html>
    )
}
