import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/Theme/Theme-provider";
import Providers from "../components/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-primary antialiased`}
      >
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system">
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
