import type { Metadata } from "next";
import "./globals.scss";
// app/layout.tsx hoặc pages/_app.tsx
import "swiper/css";
import "swiper/css/grid";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/effect-fade";

import { ThemeProvider } from "../components/Theme/Theme-provider";
import Providers from "../components/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-primary antialiased`}
      >
        <main>
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="system">
              {children}
            </ThemeProvider>
          </Providers>
        </main>
      </body>
    </html>
  );
}
